version: '3.7'

services:
  db:
    image: mongo:4.2.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  filuaback:
    build:
      context: ./
      dockerfile: Dockerfile
      network: host
    image: douglaspires/filua-back:latest
    links:
      - db
    depends_on:
      - db
    ports:
      - 80:3000
    environment:
      - MONGO_DB_CONNECTION=mongodb://db:27017/filua
      - AWS_ACCESS_KEY_ID=AKIAIYPJYFRHYBPQGGTA
      - AWS_SECRET_ACCESS_KEY=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
volumes:
  mongo_data:
