version: '3.7'

services:
  db:
    image: mongo:4.2.0
    restart: always
    ports:
      - 27017:27017
  filuaback:
    build:
      dockerfile: Dockerfile
      network: host
    image: filua-back:latest
    links:
      - db
    depends_on:
      - db
    ports:
      - 80:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_DB_CONNECTION=mongodb://localhost:27017/filua
      - AWS_ACCESS_KEY_ID=AKIAIYPJYFRHYBPQGGTA
      - AWS_SECRET_ACCESS_KEY=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
