# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:12.9
      - image: mongo:4.2.0
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install application
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build and push Docker image
          command: |
            docker build -t douglaspires/filua-back:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push douglaspires/filua-back:latest
      - run:
        name: Deploy app to Digital Ocean Server via Docker
        command: |
          ssh -o StrictHostKeyChecking=no $CIRCLE_CI_USER@$FILUA_DNS "/bin/bash ./deploy_app.sh"